Bump dependencies: web3modal and wagmi
iExecBlockchainComputing/web3mail-usecase-demo pull request #62
Opened 2023-12-04 15:26 UTC by cedric25

We currently use `@web3modal/ethereum` (https://www.npmjs.com/package/@web3modal/ethereum)

<img width="681" alt="This package has been deprecated" src="https://github.com/iExecBlockchainComputing/web3mail-usecase-demo/assets/4280765/065a6bbe-51aa-4003-98b0-6ebfae4da523">

To be used instead: https://github.com/WalletConnect/web3modal

➕ bump other related dependencies in the process.

Login avant :

<img width="1200" alt="Login before" src="https://github.com/iExecBlockchainComputing/web3mail-usecase-demo/assets/4280765/2b7a8a75-5a3d-4b43-8f9e-121a4618d1ec">

Login après :

<img width="1199" alt="Login after" src="https://github.com/iExecBlockchainComputing/web3mail-usecase-demo/assets/4280765/6d3ba0be-1505-476e-bf25-8ac118e0129d">

2023-12-04 15:43 UTC, cedric25 commented on src/App.tsx
> +  }, [connector, chain]);
Here to watch what happens in the Metamask extension.
 - Disconnecting the wallet
 - Changing wallet
 - Changing chain

All should be supported = UI should react accordingly.

2023-12-04 15:47 UTC, cedric25 commented on src/features/loginGuard/LoginGuard.tsx
> +            </div>
For example when user rejects changing chain:

<img width="675" alt="Capture d’écran 2023-12-04 à 16 45 30" src="https://github.com/iExecBlockchainComputing/web3mail-usecase-demo/assets/4280765/275dbe48-2d4f-40ef-8caa-298f91a1eaee">

2023-12-04 15:48 UTC, cedric25 commented on src/main.tsx
> -          <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
That is now done with `createWeb3Modal()` at the end of "wagmiConfig.ts" file.

2023-12-14 17:20 UTC, PierreJeanjacquot requested changes
Great work
I tested all the tricky cases I'm awaire of (account/chain switch from plugin, disconnect...) it seem's to work properly :+1: 

2 small changes to address (see comments)
- cypress ts crashing due to ts upgrade
- version in package-lock.json outdated

After the proposed cypress fix, test are still falling due to:
- the wagmi modal being different (tests to update to click the METAMAK button properly)
- the mocked metamask not being detected by wagmi (to investigate)
I suggest investigating the test cases issue in another PR

2023-12-15 08:42 UTC, cedric25 commented on package-lock.json
I've added the "module" field in this specific Cypress tsconfig file 👍

2023-12-15 11:45 UTC, PierreJeanjacquot approved these changes
LGTM, tests to fix in a next PR

2023-12-15 11:45 UTC, merged